name: 12-hours-cron
on:
  schedule:
    - cron: '33 8/12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: call-redeploy
        run: |
          curl -X POST -d {} ${{ secrets.VERCEL_BLOG_BUILD_HOOK }}