name: 12-hours-cron
on:
  schedule:
    - cron: '33 8/12 * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: call-redeploy
        run: |
          curl -X POST -d {} ${{ secrets.VERCEL_BLOG_BUILD_HOOK }}
